<?php

/**
 * @file
 * Contains nmma_forms.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function nmma_forms_preprocess_page(&$variables) {
  $variables['newsletter_form'] = \Drupal::formBuilder()->getForm('Drupal\nmma_forms\Form\Newsletter');
}

/**
 * Implements hook_library_info_alter().
 */
function nmma_forms_library_info_alter(&$libraries, $extension) {
  // The clientside_validation_jquery module doesn't set the right path to
  // additional methods.
  if (isset($libraries['jquery.validate']['js'])) {
    $libraries['jquery.validate']['js'] = [
      'js/lib/jquery.validate.js' => [],
      'js/lib/additional-methods.js' => [],
    ];
  }
}

/**
 * Implements hook_preprocess_input().
 */
function nmma_forms_preprocess_input(&$variables, $hook) {
  if (in_array($variables['element']['#type'], ['checkbox', 'radio'])) {
    $variables['#attached']['library'][] = 'nmma_forms/toggle';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nmma_forms_preprocess_cshs_select(&$variables) {
  $variables['#attached']['library'][] = 'nmma_forms/cshs';
}
