<?php

/**
 * @file
 * Contains nmma_boat_finder.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nmma_boat_finder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nmma_boat_finder module.
    case 'help.page.nmma_boat_finder':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Boat Finder Application') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nmma_boat_finder_theme() {
  return [
    'nmma_boat_finder' => [
      'render element' => 'children',
    ],
  ];
}
