module:
  acquia_purge: 0
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  anchor_link: 0
  auto_entitylabel: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_field: 0
  boatshow_boatfinder: 0
  breakpoint: 0
  bricks: 0
  bricks_default: 0
  bricks_inline: 0
  captcha: 0
  cer: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_accordion: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  codemirror_editor: 0
  colossal_menu: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  consumers: 0
  contact: 0
  contact_storage: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  cshs: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  eck: 0
  editor: 0
  editor_advanced_link: 0
  editor_file: 0
  embed: 0
  encryption: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference: 0
  eu_cookie_compliance: 0
  faqfield: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  gtm: 0
  help: 0
  history: 0
  honeypot: 0
  iframe: 0
  image: 0
  image_captcha: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonapi: 0
  knockout: 0
  language: 0
  layout_discovery: 0
  lightning_api: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_media: 0
  lightning_media_bulk_upload: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_page: 0
  lightning_roles: 0
  lightning_scheduler: 0
  lightning_search: 0
  lightning_workflow: 0
  link: 0
  linkit: 0
  machine_name_widget: 0
  media: 0
  media_entity_browser: 0
  media_entity_download: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  media_library: 0
  memcache: 0
  menu_breadcrumb: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  module_filter: 0
  nmma_blocks: 0
  nmma_brick_layouts: 0
  nmma_seminars: 0
  nmma_users: 0
  nmma_video: 0
  nmma_webform_override_recipients: 0
  node: 0
  openapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  path: 0
  path_redirect_import: 0
  pathauto: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_ui: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  rest: 0
  restui: 0
  rh_node: 0
  rh_taxonomy: 0
  robotstxt: 0
  rpt: 0
  schemata: 0
  schemata_json_schema: 0
  search_api: 0
  search_api_db: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  simple_oauth_extras: 0
  smart_trim: 0
  structure_sync: 0
  syslog: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tracker: 0
  twig_field: 0
  twig_tweak: 0
  ultimate_cron: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wistia: 0
  viewfield: 0
  views_accordion: 0
  views_block_filter_block: 0
  views_current_path: 0
  views_field_view: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  youtube_import: 0
  menu_link_content: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  lightning: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  cog: 0
  boatshow: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
