<?php

/**
 * @file
 * Hook implementations for BoatFinder module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function boatshow_boatfinder_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  if (!empty($breadcrumb)) {
    $links = $breadcrumb->getLinks();
    if (!empty($links[1])) {
      if ($links[1]->getText() == 'Boat Finder') {
        $links[1]->setUrl(Url::fromUri('internal:/boatfinder/search'));
        $breadcrumb = new Breadcrumb();
        $breadcrumb->setLinks($links);
      }
    }
  }
}
