session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    en-CA: en-CA
    fr-CA: fr-CA
    '': null
  domains:
    en: ''
    en-CA: ''
    fr-CA: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
