language: php
dist: xenial

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php: "7.2"

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
  # Cache front end dependencies to dramatically improve build time.
  # - "docroot/themes/custom/boatshow/node_modules"

services:
- mysql

addons:
  ssh_known_hosts:
    - svn-28441.prod.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
# notifications:
#   - hipchat: [api token]@[room id or name]
#   - slack: '<account>:<token>#[channel]'

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  - nvm install 9.11.2
  - nvm use 9.11.2
  - npm install gulp -g
  - source travis_scripts/build_theme.sh
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  # Uncomment these lines to test database updates using live content.
  # - blt drupal:sync:default:site
  # - source ${BLT_DIR}/scripts/travis/run_tests
  - echo "skipping tests"

# safelist: https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
branches:
  only:
  - 2.x-master
  - 2.x-develop
  - /^release\/.+$/
  - /^hotfix\/.+$/

deploy:
  # Deploy 2.x-develop branch to DEV2
  - provider: script
    script: blt artifact:deploy --branch "dev" -n
    skip_cleanup: true
    on:
      branch: 2.x-develop
      php: 7.2
  # Deploy release/* branch to stage
  - provider: script
    script: blt artifact:deploy --branch "stage" -n
    skip_cleanup: true
    on:
      branch: release/*
      php: 7.2
  # Deploy release/* branch to stage
  - provider: script
    script: blt artifact:deploy --branch "stage" -n
    skip_cleanup: true
    on:
      branch: hotfix/*
      php: 7.2
