minimum_single: 0
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 0
jquery_selector: 'select:visible, select:not([name*=''field_accessory_type_target_id''])'
search_contains: false
disable_search: true
allow_single_deselect: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  bartik: '0'
  seven: '0'
  cog: '0'
  nmma: '0'
chosen_include: 1
_core:
  default_config_hash: JUHKHJeHl1bWXY41HMIcDR-VmAWvJ4OJycDubCkIeDU
