cookie_lifetime: 100
domain: ''
domains_option: 1
domains_list: ''
eu_only: null
eu_only_js: null
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: false
langcode: en
popup_agreed:
  value: "<h3>Thank you for accepting cookies</h3>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: rich_text
popup_agree_button_message: 'I Accept Cookies '
popup_agreed_enabled: false
popup_bg_hex: ''
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
popup_delay: 1000
show_disagree_button: true
popup_disagree_button_message: 'Privacy Policy'
popup_enabled: true
popup_find_more_button_message: 'More info'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: "<h3>Cookies</h3>\r\n\r\n<p>This site uses cookies to offer you a better browsing experience. Find out more on how we use cookies and how you can change your <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f45be10a-aca7-4b78-bca0-643d4138c34b\" href=\"/privacy-policy\" target=\"_blank\">settings</a>.</p>\r\n"
  format: rich_text
mobile_popup_info:
  value: ''
  format: rich_text
mobile_breakpoint: 768
popup_link: /privacy-policy
popup_link_new_window: true
popup_position: true
fixed_top_position: true
popup_text_hex: ''
popup_width: ''
use_bare_css: true
disagree_do_not_show_popup: false
reload_page: false
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
use_mobile_message: false
_core:
  default_config_hash: OlBvbDcm2PUT2i28p3oNpuKaUKbbK4qjfrAyYxvd0B8
method: opt_in
disagree_button_label: 'I Refuse Cookies'
disabled_javascripts: ''
whitelisted_cookies: "_ga\r\n_gat_UA-2868320-1\r\n_gid"
consent_storage_method: do_not_store
withdraw_message:
  value: "<h3>We use cookies on this site to enhance your user experience</h3>\r\n\r\n<p>You have given your consent for us to set cookies.</p>\r\n"
  format: rich_text
withdraw_action_button_label: 'Withdraw consent'
withdraw_tab_button_label: 'Privacy settings'
withdraw_enabled: false
cookie_session: 0
