determine_menu: true
disable_admin_page: true
append_current_page: true
current_page_as_link: false
append_member_page: false
member_page_as_link: false
remove_home: false
add_home: true
home_as_site_name: false
exclude_empty_url: false
menu_breadcrumb_menus:
  main:
    enabled: 1
    weight: -10
    taxattach: 0
    langhandle: 0
  activities-and-education:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  admin:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  exhibitors-consumers:
    enabled: 1
    weight: 0
    taxattach: 0
    langhandle: 0
  footer:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  general-information:
    enabled: 1
    weight: 0
    taxattach: 0
    langhandle: 0
  header-secondary-nav:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  life-on-the-water:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  mm-buying-a-boat-finder:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  mm-buying-a-boat-calc:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  mm-buying-a-boat-shopping:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  mm-owning-a-boat:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  mobile-main-navigation:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  thing-to-do:
    enabled: 1
    weight: 0
    taxattach: 0
    langhandle: 0
  tools:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  account:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
_core:
  default_config_hash: MWtaH6iqiztF4V37kZZSpw-NZBbZijdlO_xMPIUCibY
