instance_host: 'https://617-GWL-687.mktorest.com'
logging: 1
tracking_method: api_client
munchkin:
  javascript_library: //munchkin.marketo.net/munchkin.js
  api_private_key: msdEKVSPL_GAaag0mlHdXMry4ui0sCJBRkr28hbEZ5UwM7ePydUiLJH9b_5Qnnuvt7g
  partition: ''
  lead_source: ''
  account_id: kJar0-a3Enl83r7zAXTbXLzwjT3ENG3KEgFCKRPJOpMwM9Wahjxp22H4YgtSwUIPdgoUaL7Y0o2xnwNHTw
  altIds: ''
  cookieLifeDays: ''
  clickTime: ''
  cookieAnon: ''
  domainLevel: ''
  disableClickDelay: ''
  asyncOnly: ''
rest:
  batch_requests: 0
  client_id: LCh3QdJhiDiSdHHMWlJulYilPeb7FdSQSCrYhaaRXq4wM_1h9IfGsIYDffR_tydhRyz5W_-ebO6lP2y9NS-up6V9O4J5vy9-yX_hR7-J3Gl2hSwx1_w
  client_secret: BH7ynmuKIeouHk1KU8kILpKAbEVl69wGA-kcAgL-KiwwM9H6pmrBd5uiURSVFY290fLgRCITQ9qoNA-FVQhWIuP_9zLGY-rknJwhIPvzxjV4zQ
field:
  enabled_fields: {  }
tracking:
  request_path:
    mode: 0
    pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
  user_role:
    mode: 0
    roles: {  }
_core:
  default_config_hash: sN5nMAhBiZm-sR0vnVjwXwFKkEeeXC1qliYlM9CXMcI
