<?php

/**
 * @file
 * Contains nmma_megamenu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nmma_megamenu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nmma_megamenu module.
    case 'help.page.nmma_megamenu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Megamenu Implementation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nmma_megamenu_theme() {
  return [
    'nmma_megamenu' => [
      'render element' => 'children',
    ],
    'mm_link' => [
      'variables' => [
        'menu_name' => NULL,
        'items' => [],
        'attributes' => [],
        'index' => NULL,
      ],
      'template' => 'mm-link',
    ],

  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function nmma_megamenu_theme_suggestions_menu_alter(&$suggestions, &$variables) {
  if ($variables['menu_name'] == 'main') {
    $suggestions[] = 'menu__megamenu';
  }
}

/**
 * Implements template_preprocess_HOOK().
 */
function nmma_megamenu_preprocess_megamenu(&$variables) {
}
