<?php

/**
 * @file
 * Contains nmma_megamenu_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nmma_megamenu_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nmma_megamenu_blocks module.
    case 'help.page.nmma_megamenu_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates blocks for Megamenu regions.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nmma_megamenu_blocks_theme() {
  return [
    'nmma_megamenu_discoverboating' => [
      'variables' => [
        'inlineform' => NULL,
      ],
      'template' => 'discoverboating-menublock',
    ],
    'nmma_megamenu_owning_a_boat' => [
      'variables' => [],
      'template' => 'owningaboat-menublock',
    ],
    'nmma_megamenu_buying_a_boat' => [
      'variables' => [],
      'template' => 'buyingaboat-menublock',
    ],
    'nmma_megamenu_articles_and_resources' => [
      'variables' => [],
      'template' => 'articlesandresources-menublock',
    ],

  ];
}
