vagrant_hostname: local.boatshows.com
vagrant_machine_name: boatshows
vagrant_ip: 10.102.200.4
vagrant_box: geerlingguy/ubuntu1604
workspace: /root
drupal_site_name: 'Boatshows'
vagrant_synced_folders:
    -
        local_path: .
        destination: /var/www/boatshow
        type: nfs
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: /var/www/boatshow
drupal_core_path: /var/www/boatshow/docroot
ssh_home: /var/www/boatshow
apache_vhosts:
    -
        servername: '{{ drupal_domain }}'
        serveralias: 'www.{{ drupal_domain }}'
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'dashboard.{{ drupal_domain }}'
        serveralias: 'www.dashboard.{{ drupal_domain }}'
        documentroot: /var/www/dashboard
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'adminer.{{ drupal_domain }}'
        serveralias: 'www.adminer.{{ drupal_domain }}'
        documentroot: '{{ adminer_install_dir }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: local.chicago.com
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'

apache_vhosts_ssl:
    -
        servername: '{{ drupal_domain }}'
        documentroot: '{{ drupal_core_path }}'
        certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
        certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
        extra_parameters: "ProxyPassMatch ^/(.*\\.php(/.*)?)$ \"fcgi://127.0.0.1:9000{{ drupal_core_path }}\"\n"
mysql_databases:
    -
        name: drupal
        encoding: utf8
        collation: utf8_general_ci
    -
        name: boatshow
        encoding: utf8
        collation: utf8_general_ci


mysql_users:
    -
        name: drupal
        host: '%'
        password: drupal
        priv: 'drupal.*:ALL'
    -
        name: boatshow
        host: '%'
        password: boatshow
        priv: 'boatshow.*:ALL'

drupal_install_site: false
configure_drush_aliases: false
nodejs_version: 9.x
nodejs_npm_global_packages:
    -
        name: bower
    -
        name: gulp-cli
    -
        name: yarn
nodejs_install_npm_user: '{{ drupalvm_user }}'
npm_config_prefix: '/home/{{ drupalvm_user }}/.npm-global'
installed_extras:
    - adminer
    - selenium
    - drush
    - mailhog
    - memcached
    - nodejs
    - solr
    - xdebug
    - drupalconsole
php_version: '7.2'
php_packages_extra:
    - 'php{{ php_version }}-bz2'
    - 'php{{ php_version }}-imagick'
    - imagemagick
    - php7.0-sybase
    - php7.0-odbc
    - freetds-common
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_disable: 'no'
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: '9000'
php_memory_limit: 512M
solr_version: 4.5.1
post_provision_scripts:
    - ../../../acquia/blt/scripts/drupal-vm/configure-solr.sh
    - ../../../acquia/blt/scripts/drupal-vm/post-provision.php
    - ../../../../box/scripts/post-provision.php
