vagrant_hostname: local.boatshows.com
vagrant_machine_name: boatshows
vagrant_ip: 10.102.200.4
vagrant_box: geerlingguy/ubuntu1604
workspace: /root
drupal_site_name: Boatshows
vagrant_synced_folders:
  -
    local_path: .
    destination: /var/www/boatshow
    type: nfs
    mount_options: ['actimeo=2']
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: /var/www/boatshow
drupal_core_path: /var/www/boatshow/docroot
ssh_home: /var/www/boatshow
apache_vhosts:
  # default (unused)
  -
    servername: '{{ drupal_domain }}'
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # dashboard
  -
    servername: 'dashboard.{{ drupal_domain }}'
    documentroot: /var/www/dashboard
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # adminer
  -
    servername: 'adminer.{{ drupal_domain }}'
    documentroot: '{{ adminer_install_dir }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: atlantic city
  -
    servername: local.acboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: louisville
  -
    servername: local.louisvilleboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: baltimore
  -
    servername: local.baltimoreboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: miami
  -
    servername: local.miamiboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: minneapolis
  -
    servername: local.minneapolisboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: newengland
  -
    servername: local.newenglandboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  # multisite: newyork
  -
    servername: local.nyboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
  #multisite: stlouis
  -
    servername: local.stlouisboatshow.com
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
apache_vhosts_ssl:
  # default (unused but necessary to set up SSL for local hosts)
  -
    servername: '{{ drupal_domain }}'
    documentroot: '{{ drupal_core_path }}'
    certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
    certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}\n\nProxyPassMatch ^/(.*\\.php(/.*)?)$ \"fcgi://127.0.0.1:9000{{ drupal_core_path }}\"\n"
mysql_databases:
  -
    name: atlanticcity
    encoding: utf8
    collation: utf8_general_ci
  -
    name: baltimore
    encoding: utf8
    collation: utf8_general_ci
  -
    name: louisville
    encoding: utf8
    collation: utf8_general_ci
  -
    name: miami
    encoding: utf8
    collation: utf8_general_ci
  -
    name: minneapolis
    encoding: utf8
    collation: utf8_general_ci
  -
    name: newengland
    encoding: utf8
    collation: utf8_general_ci
  -
    name: newyork
    encoding: utf8
    collation: utf8_general_ci
  -
    name: stlouis
    encoding: utf8
    collation: utf8_general_ci
mysql_users: {  }
drupal_install_site: false
configure_drush_aliases: false
nodejs_version: 9.x
nodejs_npm_global_packages:
  -
    name: bower
  -
    name: gulp-cli
  -
    name: yarn
nodejs_install_npm_user: '{{ drupalvm_user }}'
npm_config_prefix: '/home/{{ drupalvm_user }}/.npm-global'
installed_extras:
  - adminer
  - drush
  - mailhog
  - memcached
  - nodejs
  - xdebug
  - drupalconsole
php_version: '7.2'
php_packages_extra:
  - 'php{{ php_version }}-bz2'
  - 'php{{ php_version }}-imagick'
  - imagemagick
  - php7.0-sybase
  - php7.0-odbc
  - freetds-common
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_disable: 'no'
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: '9000'
php_memory_limit: 512M
solr_version: 4.5.1
post_provision_scripts:
  - ../../../acquia/blt/scripts/drupal-vm/configure-solr.sh
  - ../../../acquia/blt/scripts/drupal-vm/post-provision.php
  - ../../../../box/scripts/post-provision.php
