# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

#=========================================================================
# In addition to the environment variables defined in this file, also
# add the following variables in the Circle CI UI.
#
# See: https://circleci.com/docs/2.0/environment-variables/
#
# ACQUIA_HOSTNAME: The FQDN of the REMOTE git repository on Acquia.
# GIT_EMAIL:       The email address applied when making commits.
# GIT_NAME:        The user name applied when making commits.
#=========================================================================

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.23-apache-node-browsers-legacy
    steps:
      - checkout
      - run: sudo apt-get install -y libbz2-dev libpng-dev
      - run: sudo docker-php-ext-install bz2 gd
      - run: composer install
      - run: vendor/acquia/blt/bin/blt frontend:setup --no-interaction
      - run: vendor/acquia/blt/bin/blt frontend:build --no-interaction
      - run: vendor/acquia/blt/bin/blt frontend:setup --site=boatshow --no-interaction
      - run: vendor/acquia/blt/bin/blt frontend:build --site=boatshow --no-interaction
      - run: vendor/acquia/blt/bin/blt artifact:build --site=boatshow --no-interaction

  deploy:
    docker:
      - image: circleci/php:7.1.23-apache-node-browsers-legacy
    steps:
      - checkout
      - run: sudo apt-get install -y libbz2-dev libpng-dev
      - run: sudo docker-php-ext-install bz2 gd
      - run: composer install
      - run: echo -e "Host $ACQUIA_HOSTNAME\n  StrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git config --global user.email "$GIT_EMAIL"
      - run: git config --global user.name "$GIT_NAME"
      - add_ssh_keys:
          fingerprints:
            - "cd:aa:f0:7a:24:4e:3d:06:f8:bc:3d:a3:64:04:40:6c"
      - run: vendor/acquia/blt/bin/blt frontend:setup --no-interaction
      - run: vendor/acquia/blt/bin/blt frontend:build --no-interaction
      - run: vendor/acquia/blt/bin/blt frontend:setup --site=boatshow --no-interaction
      - run: vendor/acquia/blt/bin/blt frontend:build --site=boatshow --no-interaction
      - run: git commit -am "Automated deployment from CircleCI."
      - run: vendor/acquia/blt/bin/blt artifact:deploy --site=boatshow --no-interaction

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
      - deploy:
          filters:
            branches:
              only:
                - develop
