<?php

use Drupal\Core\Session\AccountInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Access\AccessResultInterface;

use Drupal\Core\Access\AccessResult;
use Drupal\node\NodeInterface;
/**
 * @file
 * Contains Drupal\nmmacontentaccess\nmmacontentaccess.module.
 */

/**
 * @defgroup nmmacontentaccess Example: nmmacontentaccess node
 * @ingroup examples
 * @{
 * Implement a content entity.
 *
 * This module demonstrates implementing a nmmacontentaccess node.
 *
 * Entity API is the API that stores pieces of content and configuration for
 * Drupal core. For instance, if you've encountered node content types, you've
 * encountered entities of type 'node.'
 *
 * This example implements the Entity API so that we have an entity type usable
 * by the user which you might think of as specialized nodes, but which are
 * different from nodes. These entities are called NmmaNode, and are known
 * internally by the machine name nmmacontentaccess_node.
 *
 * NmmaNode is a fieldable content entity used to hold structured information
 * without the overhead of using a node content type. 'Fieldable' means you can
 * attach fields to it, like you can with nodes. It is defined programmatically
 * (completely in code). We will show the main techniques to handle and expose
 * the contents of this entity type.
 *
 * The NmmaNode entity will demonstrate the main tasks for an entity:
 * - define
 * - save
 * - load
 * - view
 * - edit
 * - delete
 * - control access
 *
 * Where ever possible, we use the amazing tools built into D8 natively.
 *
 * @see Drupal\nmmacontentaccess\Entity\NmmaNode
 * @see config_entity_example
 * }
 */

 /**
 * Implements hook_node_access().
 *
 * Enforces our access rules for custom workflow target content to force updates
 * only if the user is targeted in the user select field
 */
 function nmmacontentaccess_node_access($node, $op, $account) {
   // If a node is being updated
   if ($op == 'update' || $op == 'delete') {
     // If the user select field exists on this node
     if (!in_array('PR', $account->getRoles())) {
           return AccessResult::forbidden();
     }
   }
   // Else ignore altering access
   //return NODE_ACCESS_IGNORE;
}
