<?php

/**
 * @file
 * Contains nmma_go_boating_map.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nmma_go_boating_map_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nmma_go_boating_map module.
    case 'help.page.nmma_go_boating_map':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Implementation of Marina Finder Map') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nmma_go_boating_map_theme() {
  $build = [
    'boating_map' => [
      'variables' => [],
      'template' => 'boating-map',
    ],
  ];

  return $build;
}

/**
 * Implements hook_preprocess_region().
 */
function nmma_go_boating_map_preprocess_region(&$variables) {
  if ($variables['region'] === 'megamenu_1') {
    $variables['go_boating_inline_form'] = \Drupal::formBuilder()->getForm('Drupal\nmma_go_boating_map\Form\GoBoatingInline');
  }
}

/**
 * Implements hook_preprocess_nmma_megamenu_discoverboating().
 */
function nmma_go_boating_map_preprocess_nmma_megamenu_discoverboating(&$variables) {
  $variables['inlineform'] = \Drupal::formBuilder()->getForm('Drupal\nmma_go_boating_map\Form\GoBoatingInline');
}
