<?php

/**
 * @file
 * Contains nmma_newsletter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nmma_newsletter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nmma_newsletter module.
    case 'help.page.nmma_newsletter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles newsletter signup. Passes data to Marketo endpoint.') . '</p>';
      return $output;

    default:
  }
}
