menus:
  -
    menu_name: mm-owning-a-boat
    title: 'Insuring Your Boat'
    parent: null
    uri: 'entity:node/406'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 13e87fb7-d1b3-4bfb-ab97-5421001660d4
    options: null
  -
    menu_name: mm-owning-a-boat
    title: 'Towing & Trailering'
    parent: null
    uri: 'entity:node/17461'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: b07436e2-ffd4-4cd7-b5e1-dd8d1587826e
    options: null
  -
    menu_name: mm-owning-a-boat
    title: 'Storing Your Boat'
    parent: null
    uri: 'entity:node/17701'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: e3f48c7b-6c6e-4038-8540-1764170cf1c1
    options: null
  -
    menu_name: mm-owning-a-boat
    title: 'Boat Maintenance'
    parent: null
    uri: 'entity:node/581'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: d86bb49a-d0d2-4ca2-8791-31f983fb4c6d
    options: null
  -
    menu_name: mm-owning-a-boat
    title: Safety
    parent: null
    uri: 'entity:node/881'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 6ff090af-02a0-4250-9d5f-6f3df4ca2361
    options: null
  -
    menu_name: mm-owning-a-boat
    title: 'Responsible Boating'
    parent: null
    uri: 'entity:node/3276'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 9fe258eb-ff3d-4317-bd9f-3fb5e6754c0c
    options: null
  -
    menu_name: mm-buying-a-boat-shopping
    title: 'Certified Dealers'
    parent: null
    uri: 'internal:/certified-dealers'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: 162bbb86-ab4e-4afe-8059-20b7c29970de
    options: null
  -
    menu_name: mm-buying-a-boat-shopping
    title: 'Shopping for a Boat'
    parent: null
    uri: 'internal:/videos/shopping-your-boat'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: 84ab9020-d27c-495f-8db8-1928c096cfc9
    options: null
  -
    menu_name: mm-buying-a-boat-shopping
    title: 'Find a Marina'
    parent: null
    uri: 'internal:/marina-finder'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: 8b6b98b7-99fc-4971-b995-7f1ac441987a
    options: null
  -
    menu_name: mm-buying-a-boat-shopping
    title: 'Boat Shows'
    parent: null
    uri: 'http://www.boatshows.com/Calendar#'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: en
    uuid: 41a7b3ba-ad5c-42b5-b696-af31d6ca72a5
    options: null
  -
    menu_name: mm-buying-a-boat-calc
    title: 'Boat Loan Calculator'
    parent: null
    uri: 'entity:node/16076'
    link_title: ''
    description: 'Boat Loan Calculator'
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: ad49884c-8e6f-438c-8667-78c9dff1c2a8
    options: null
  -
    menu_name: mm-buying-a-boat-calc
    title: 'Costs of Boat Ownership'
    parent: null
    uri: 'internal:/videos/boating-guy-what-are-costs-boat-ownership'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: aa21f18f-04db-4105-8b10-ad39cb291ad1
    options: null
  -
    menu_name: mm-buying-a-boat-calc
    title: 'Financing Your Boat'
    parent: null
    uri: 'internal:/videos/financing-and-insuring'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: a7e1e03e-3a90-4791-9267-6803c3411d9c
    options: null
  -
    menu_name: mm-buying-a-boat-calc
    title: 'New or Pre Owned'
    parent: null
    uri: 'internal:/videos/new-or-pre-owned-boat-canadian-boating-guy-english'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: f96ba4f0-5aad-487d-b2a8-f3ce84744dba
    options: null
  -
    menu_name: mm-buying-a-boat-calc
    title: 'Buying a Pre-Owned Boat'
    parent: null
    uri: 'internal:/resources/considering-a-pre-owned-boat-these-tips-will-start-you-on-the-right-path'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: f152683e-dd03-4c8a-8701-3af6a5cd15f1
    options: null
  -
    menu_name: mm-buying-a-boat-finder
    title: 'Boat Finder'
    parent: null
    uri: 'entity:node/71'
    link_title: ''
    description: 'Find the Boat that''s right for you'
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: eceb1df0-0160-4832-a9b3-e47271ff9759
    options: null
  -
    menu_name: mm-buying-a-boat-finder
    title: 'Boat Brands & Manufacturers'
    parent: null
    uri: 'entity:node/17816'
    link_title: ''
    description: 'Find Boats and the Manufacturers who make them '
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: faab4f10-ce2c-426f-b55f-e64bc934aa20
    options: null
  -
    menu_name: mm-buying-a-boat-finder
    title: 'Certified Boats'
    parent: null
    uri: 'internal:/buying/certified-boats'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: 5773c1c2-faee-4a01-b204-7a78051a2dee
    options: null
  -
    menu_name: mm-buying-a-boat-finder
    title: Engines
    parent: null
    uri: 'internal:/buying/boat-motors'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: en
    uuid: 25b6d1fd-a659-4e50-bc52-89f8de9efcd6
    options: null
  -
    menu_name: mm-buying-a-boat-finder
    title: FAQs
    parent: null
    uri: 'internal:/buying/boat-faq'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 08859605-7b7d-4897-ac64-3a150db88eb2
    options: null
  -
    menu_name: activities-and-education
    title: 'Freshwater Fishing'
    parent: null
    uri: 'internal:/activities/freshwater-fishing'
    link_title: ''
    description: 'Freshwater Fishing'
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: a471d452-8db6-42a3-a0c8-ab2b4c823c40
    options: null
  -
    menu_name: activities-and-education
    title: 'Saltwater Fishing'
    parent: null
    uri: 'internal:/activities/saltwater-fishing'
    link_title: ''
    description: 'Saltwater Fishing'
    enabled: '1'
    expanded: '0'
    weight: '2'
    langcode: en
    uuid: b9ae7bc8-10aa-483b-9170-187de6890c29
    options: null
  -
    menu_name: activities-and-education
    title: Watersports
    parent: null
    uri: 'internal:/activities/watersports'
    link_title: ''
    description: Watersports
    enabled: '1'
    expanded: '0'
    weight: '2'
    langcode: en
    uuid: b23bc085-5c99-41a8-a0bd-1d673c83c0cf
    options: null
  -
    menu_name: activities-and-education
    title: Sailing
    parent: null
    uri: 'internal:/activities/sailing'
    link_title: ''
    description: Sailing
    enabled: '1'
    expanded: '0'
    weight: '3'
    langcode: en
    uuid: 1b89efe7-f0db-4027-83ae-04207e4a5d13
    options: null
  -
    menu_name: activities-and-education
    title: 'Education & Training'
    parent: null
    uri: 'entity:node/17846'
    link_title: ''
    description: 'Boating Education and Boating Training'
    enabled: '1'
    expanded: '0'
    weight: '5'
    langcode: en
    uuid: 9c0c5bcd-7d9e-494d-995e-efcdbfea17d0
    options: null
  -
    menu_name: life-on-the-water
    title: 'High Speed Holiday'
    parent: null
    uri: 'entity:node/17806'
    link_title: ''
    description: 'Take a Boating Vacation!'
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 180395c2-fd87-45ac-ab39-38a9dcebf820
    options: null
  -
    menu_name: life-on-the-water
    title: 'Get Away From It All'
    parent: null
    uri: 'entity:node/17821'
    link_title: ''
    description: 'Escape With A New Boat'
    enabled: '1'
    expanded: '0'
    weight: '1'
    langcode: en
    uuid: 59e0937c-6653-4f8f-8f98-7e8e329554fb
    options: null
  -
    menu_name: life-on-the-water
    title: 'Keys To The Good Life'
    parent: null
    uri: 'entity:node/17826'
    link_title: ''
    description: 'Keeys to the Good Life'
    enabled: '1'
    expanded: '0'
    weight: '2'
    langcode: en
    uuid: c4d9d93b-dcf0-43d8-8cfb-7c97c54c92c9
    options: null
  -
    menu_name: life-on-the-water
    title: 'Refresh Your Relationships'
    parent: null
    uri: 'entity:node/17831'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '5'
    langcode: en
    uuid: 1e942bf2-b1fc-46bd-92cd-28d045f4830f
    options: null
  -
    menu_name: life-on-the-water
    title: 'A Family Tradition'
    parent: null
    uri: 'entity:node/17836'
    link_title: ''
    description: 'A Family Tradition'
    enabled: '1'
    expanded: '0'
    weight: '6'
    langcode: en
    uuid: ef1dc701-0e6b-4465-aeaa-26d182c72045
    options: null
  -
    menu_name: life-on-the-water
    title: 'Weekends On The Water'
    parent: null
    uri: 'entity:node/17841'
    link_title: ''
    description: 'Weekends On The Water'
    enabled: '1'
    expanded: '0'
    weight: '8'
    langcode: en
    uuid: 7fda2b5a-4919-4b11-a497-b22a425e3170
    options: null
  -
    menu_name: footer
    title: 'About Us'
    parent: null
    uri: 'entity:node/17251'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: b336e3ea-0945-42b3-b15c-38565b83ce4a
    options: null
  -
    menu_name: footer
    title: 'Visit Our Canadian Site'
    parent: null
    uri: 'https://www.discoverboating.ca'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 037e2ce0-a92c-4d0c-ab52-ba659cf7be55
    options: null
  -
    menu_name: footer
    title: Sitemap
    parent: null
    uri: 'internal:/sitemap'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: c7cc3737-4adf-465d-a300-3b5ef2c32145
    options: null
  -
    menu_name: footer
    title: LogIn
    parent: null
    uri: 'internal:/user/login'
    link_title: ''
    description: 'Admin login'
    enabled: '1'
    expanded: '0'
    weight: '7'
    langcode: en
    uuid: ef7e663c-9aae-463c-a3cf-ef35a29cda31
    options: null
  -
    menu_name: footer
    title: 'Privacy Policy'
    parent: 'menu_link_content:5a9a19aa-e044-41c3-8843-00b2c2d37c21'
    uri: 'entity:node/17906'
    link_title: null
    description: 'Privacy Policy'
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: f598a164-9c00-4385-ab3b-340ae65d80eb
    options: null
  -
    menu_name: main
    title: 'Discover Boating'
    parent: null
    uri: 'entity:node/91'
    link_title: ''
    description: 'Discover Boating'
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: c7a5bc7b-6154-43b2-9bb5-9d9e29dbefe2
    options: null
  -
    menu_name: main
    title: 'Buying a Boat'
    parent: null
    uri: 'entity:node/81'
    link_title: ''
    description: 'Buying a Boat'
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: 630ba2e5-cc80-477f-a099-b88920ae7570
    options: null
  -
    menu_name: main
    title: 'Owning a Boat'
    parent: null
    uri: 'entity:node/86'
    link_title: ''
    description: 'Owning a Boat'
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: adf5e570-3e6a-4478-be4d-145630cfc27c
    options: null
  -
    menu_name: main
    title: 'Articles & Resources'
    parent: null
    uri: 'internal:/articles-and-resources'
    link_title: ''
    description: 'Owning a Boat'
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: en
    uuid: ad01d261-4626-44ac-91ee-e698f81417fd
    options: null
