field.field_settings.twig:
  type: mapping
  label: Twif field settings
  mapping:
    display_mode:
      type: string
      label: Display mode

field.value.twig:
  type: mapping
  label: Default value
  mapping:
    value:
      type: string
      label: Twig template

field.widget.settings.twig:
  type: field.widget.settings.codemirror_editor
