name: Flood settings
type: module
description: Provides a ready-to-use UI for flood settings.
core: 8.x
core_version_requirement: ^8 || ^9
php: 7.1
package: Spam control
configure: flood_settings.settings

# Information added by Drupal.org packaging script on 2020-04-09
version: '8.x-1.0-rc1'
project: 'flood_settings'
datestamp: 1586417950
